// Copyright © 2026, Sean Ford and the Python on Viya contributors
// SPDX-License-Identifier: Apache-2.0

import assert from "node:assert/strict";

import { scanSasProfiles } from "../../src/profile/import";
import { CURRENT_PROFILE_VERSION } from "../../src/profile/model";

/**
 * The import reads a shape this project does not own, written by an extension
 * that ships on its own schedule. So the property under test is not really "does
 * it map the fields" — it is "is it total": every entry gets an answer, nothing
 * throws, nothing is written, and an input nobody anticipated costs a skipped row
 * rather than a broken command.
 *
 * The ids are generated by an injected counter rather than `randomUUID`, which
 * is why these tests can assert on whole objects instead of matching them against
 * a pattern.
 */

/** A deterministic stand-in for `randomUUID`. */
function counter(): (name: string) => string {
  let n = 0;
  return () => `id-${String(++n)}`;
}

const rest = (endpoint: string): Record<string, unknown> => ({
  connectionType: "rest",
  endpoint,
});

describe("scanSasProfiles", () => {
  it("maps a REST profile into ours, secret excluded", () => {
    const { candidates, skipped } = scanSasProfiles(
      {
        activeProfile: "Prod",
        profiles: {
          Prod: {
            connectionType: "rest",
            endpoint: "https://viya.example.com/",
            context: "SAS Job Execution compute context",
            clientId: "my-client",
            // Present so the assertion below can prove it is read as a boolean
            // and never carried into the candidate. The value is a placeholder.
            clientSecret: "not-copied",
          },
        },
      },
      { makeId: counter() },
    );

    assert.deepEqual(skipped, []);
    assert.deepEqual(candidates, [
      {
        name: "Prod",
        originalName: "Prod",
        profile: {
          version: CURRENT_PROFILE_VERSION,
          id: "id-1",
          endpoint: "https://viya.example.com",
          context: "SAS Job Execution compute context",
          clientId: "my-client",
        },
        hadClientSecret: true,
      },
    ]);
  });

  it("reports the presence of a secret without carrying its value anywhere", () => {
    const { candidates } = scanSasProfiles(
      { profiles: { A: rest("https://a.example.com") } },
      { makeId: counter() },
    );
    // Asserted as a whole object rather than field by field: `deepEqual` fails
    // on an *extra* key too, which is what proves no secret came along.
    assert.deepEqual(candidates, [
      {
        name: "A",
        originalName: "A",
        profile: {
          version: CURRENT_PROFILE_VERSION,
          id: "id-1",
          endpoint: "https://a.example.com",
        },
        hadClientSecret: false,
      },
    ]);
  });

  it("skips the three SAS 9 transports, saying which one it was", () => {
    const { candidates, skipped } = scanSasProfiles(
      {
        profiles: {
          OverSsh: { connectionType: "ssh", host: "sas9.example.com" },
          OverCom: { connectionType: "com", host: "sas9.example.com" },
          OverIom: { connectionType: "iom", host: "sas9.example.com" },
        },
      },
      { makeId: counter() },
    );

    assert.deepEqual(candidates, []);
    assert.deepEqual(
      skipped.map((entry) => entry.name),
      ["OverSsh", "OverCom", "OverIom"],
    );
    assert.match(skipped[0]?.reason ?? "", /ssh/);
    assert.match(skipped[0]?.reason ?? "", /SAS 9/);
  });

  it("infers a missing connection type from the fields, not from a default", () => {
    // Upstream's migration defaults an absent `connectionType` to `rest`
    // unconditionally, which mislabels the SAS 9 profiles that predate the
    // field. Reading a file we do not own, a wrong guess must cost a skipped row.
    const { candidates, skipped } = scanSasProfiles(
      {
        profiles: {
          LegacyViya: { endpoint: "https://viya.example.com" },
          LegacySsh: { host: "sas9.example.com", saspath: "/opt/sas" },
          Empty: {},
        },
      },
      { makeId: counter() },
    );

    assert.deepEqual(
      candidates.map((candidate) => candidate.name),
      ["LegacyViya"],
    );
    assert.deepEqual(
      skipped.map((entry) => entry.name),
      ["LegacySsh", "Empty"],
    );
    assert.match(
      skipped[1]?.reason ?? "",
      /no connection type and no endpoint/,
    );
  });

  it("skips a REST profile whose endpoint we would refuse to store", () => {
    const { candidates, skipped } = scanSasProfiles(
      {
        profiles: {
          Cleartext: rest("http://viya.example.com"),
          WithCredentials: rest("https://user:pw@viya.example.com"),
        },
      },
      { makeId: counter() },
    );
    assert.deepEqual(candidates, []);
    assert.equal(skipped.length, 2);
  });

  it("renames around a collision, saying where the profile came from", () => {
    const { candidates } = scanSasProfiles(
      { profiles: { Prod: rest("https://viya.example.com") } },
      { makeId: counter(), existingNames: ["prod"] },
    );
    assert.deepEqual(
      candidates.map((candidate) => [candidate.originalName, candidate.name]),
      [["Prod", "Prod (SAS)"]],
    );
  });

  it("counts only once the origin suffix has itself collided", () => {
    const { candidates } = scanSasProfiles(
      { profiles: { Prod: rest("https://viya.example.com") } },
      { makeId: counter(), existingNames: ["Prod", "Prod (SAS)"] },
    );
    assert.equal(candidates[0]?.name, "Prod (SAS 2)");
  });

  it("does not let two imported profiles collide with each other", () => {
    const { candidates } = scanSasProfiles(
      {
        profiles: {
          Prod: rest("https://a.example.com"),
          prod: rest("https://b.example.com"),
        },
      },
      { makeId: counter() },
    );
    assert.deepEqual(
      candidates.map((candidate) => candidate.name),
      ["Prod", "prod (SAS)"],
    );
  });

  it("accepts a bare dictionary as well as their wrapper object", () => {
    // A hand-copied fragment is a plausible thing to be handed, and refusing it
    // would fail in a way that looks like "the import is broken".
    const { candidates } = scanSasProfiles(
      { Prod: rest("https://viya.example.com") },
      { makeId: counter() },
    );
    assert.equal(candidates.length, 1);
  });

  it("never treats their activeProfile string as a profile", () => {
    const { candidates, skipped } = scanSasProfiles(
      { activeProfile: "Prod" },
      { makeId: counter() },
    );
    assert.deepEqual(candidates, []);
    assert.deepEqual(skipped, []);
  });

  it("returns empty for anything that is not an object at all", () => {
    for (const raw of [undefined, null, "nonsense", 7, ["a"]]) {
      assert.deepEqual(scanSasProfiles(raw, { makeId: counter() }), {
        candidates: [],
        skipped: [],
      });
    }
  });

  it("does not mutate what it was given", () => {
    const raw = {
      profiles: {
        Prod: { connectionType: "rest", endpoint: "viya.example.com/" },
      },
    };
    const before = JSON.stringify(raw);
    scanSasProfiles(raw, { makeId: counter(), existingNames: ["Prod"] });
    assert.equal(JSON.stringify(raw), before);
  });
});
